export const currentUser = {
  id: "u1",
  name: "Alicia Grant",
  email: "alicia@luma.chat",
  role: "Product Lead",
  avatar: "AG",
  color: "from-violet-500 to-indigo-500",
  status: "online",
  bio: "Building tools that help teams move faster.",
  phone: "+1 (415) 555-0148",
  location: "San Francisco, CA",
};

export const users = [
  {
    id: "u1",
    name: "Alicia Grant",
    email: "alicia@luma.chat",
    avatar: "AG",
    color: "from-violet-500 to-indigo-500",
    status: "online",
  },
  {
    id: "u2",
    name: "Noah Patel",
    email: "noah@luma.chat",
    avatar: "NP",
    color: "from-emerald-500 to-teal-500",
    status: "online",
  },
  {
    id: "u3",
    name: "Maya Chen",
    email: "maya@luma.chat",
    avatar: "MC",
    color: "from-amber-500 to-orange-500",
    status: "away",
  },
  {
    id: "u4",
    name: "Leo Martinez",
    email: "leo@luma.chat",
    avatar: "LM",
    color: "from-cyan-500 to-sky-500",
    status: "offline",
  },
  {
    id: "u5",
    name: "Jules Carter",
    email: "jules@luma.chat",
    avatar: "JC",
    color: "from-pink-500 to-rose-500",
    status: "online",
  },
  {
    id: "u6",
    name: "Ari Johnson",
    email: "ari@luma.chat",
    avatar: "AJ",
    color: "from-slate-500 to-gray-500",
    status: "offline",
  },
  {
    id: "u7",
    name: "Priya Raman",
    email: "priya@luma.chat",
    avatar: "PR",
    color: "from-fuchsia-500 to-purple-500",
    status: "online",
  },
  {
    id: "u8",
    name: "Nora James",
    email: "nora@luma.chat",
    avatar: "NJ",
    color: "from-red-500 to-pink-500",
    status: "online",
  },
];

export const conversations = [
  {
    id: "c1",
    type: "DIRECT",
    title: "Noah Patel",
    avatar: "NP",
    color: "from-emerald-500 to-teal-500",
    members: ["u1", "u2"],
    status: "online",
    unreadCount: 2,
    lastMessage: {
      id: "m10",
      senderId: "u2",
      text: "The launch checklist is ready for review when you have a minute.",
      createdAt: "2026-09-02T09:38:00.000Z",
      status: "DELIVERED",
    },
    description: "Product launch coordination",
  },
  {
    id: "c2",
    type: "GROUP",
    title: "Product Launch",
    avatar: "PL",
    color: "from-indigo-500 to-violet-500",
    members: ["u1", "u2", "u3", "u5", "u7"],
    status: "online",
    unreadCount: 3,
    lastMessage: {
      id: "m20",
      senderId: "u5",
      text: "I updated the landing page copy and added the final CTA notes.",
      createdAt: "2026-09-02T09:21:00.000Z",
      status: "READ",
    },
    description: "Cross-functional launch team",
  },
  {
    id: "c3",
    type: "DIRECT",
    title: "Maya Chen",
    avatar: "MC",
    color: "from-amber-500 to-orange-500",
    members: ["u1", "u3"],
    status: "away",
    unreadCount: 0,
    lastMessage: {
      id: "m30",
      senderId: "u1",
      text: "Thanks for the feedback on the onboarding flow.",
      createdAt: "2026-09-02T08:12:00.000Z",
      status: "READ",
    },
    description: "Design feedback loop",
  },
  {
    id: "c4",
    type: "GROUP",
    title: "Customer Success",
    avatar: "CS",
    color: "from-emerald-500 to-lime-500",
    members: ["u1", "u4", "u6", "u8"],
    status: "offline",
    unreadCount: 0,
    lastMessage: {
      id: "m40",
      senderId: "u8",
      text: "Customer health snapshot is posted in the workspace.",
      createdAt: "2026-09-01T18:40:00.000Z",
      status: "READ",
    },
    description: "Support and retention team",
  },
  {
    id: "c5",
    type: "DIRECT",
    title: "Leo Martinez",
    avatar: "LM",
    color: "from-cyan-500 to-sky-500",
    members: ["u1", "u4"],
    status: "offline",
    unreadCount: 0,
    lastMessage: {
      id: "m50",
      senderId: "u4",
      text: "Let’s sync on the follow-up notes tomorrow.",
      createdAt: "2026-09-01T13:15:00.000Z",
      status: "READ",
    },
    description: "Engineering planning",
  },
];

export const messagesByConversation = {
  c1: [
    {
      id: "m1",
      senderId: "u2",
      senderName: "Noah Patel",
      text: "Hey Alicia, the rollout timeline looks solid. Can we tighten the QA check before Friday?",
      createdAt: "2026-09-02T09:02:00.000Z",
      status: "READ",
    },
    {
      id: "m2",
      senderId: "u1",
      senderName: "Alicia Grant",
      text: "Absolutely. I’ve scheduled the final QA review for tomorrow afternoon and we can call out anything risky.",
      createdAt: "2026-09-02T09:04:00.000Z",
      status: "READ",
      readBy: ["u2"],
    },
    {
      id: "m3",
      senderId: "u2",
      senderName: "Noah Patel",
      text: "Perfect. I’m going to prepare the launch checklist and share it in the thread.",
      createdAt: "2026-09-02T09:32:00.000Z",
      status: "DELIVERED",
    },
    {
      id: "m4",
      senderId: "u2",
      senderName: "Noah Patel",
      text: "The launch checklist is ready for review when you have a minute.",
      createdAt: "2026-09-02T09:38:00.000Z",
      status: "DELIVERED",
    },
  ],
  c2: [
    {
      id: "m11",
      senderId: "u3",
      senderName: "Maya Chen",
      text: "I tightened the animation timing and it feels much more natural on mobile.",
      createdAt: "2026-09-02T08:55:00.000Z",
      status: "READ",
    },
    {
      id: "m12",
      senderId: "u1",
      senderName: "Alicia Grant",
      text: "Love it. Let’s keep the motion subtle and make sure the copy stays consistent with the campaign.",
      createdAt: "2026-09-02T08:58:00.000Z",
      status: "READ",
      readBy: ["u3", "u5"],
    },
    {
      id: "m13",
      senderId: "u5",
      senderName: "Jules Carter",
      text: "I updated the landing page copy and added the final CTA notes.",
      createdAt: "2026-09-02T09:21:00.000Z",
      status: "READ",
    },
    {
      id: "m14",
      senderId: "u7",
      senderName: "Priya Raman",
      text: "The analytics events are firing correctly in staging. I’m ready for sign-off.",
      createdAt: "2026-09-02T09:25:00.000Z",
      status: "DELIVERED",
    },
  ],
  c3: [
    {
      id: "m21",
      senderId: "u3",
      senderName: "Maya Chen",
      text: "The new onboarding card hierarchy reads better now. I can share the revised mock in 10 minutes.",
      createdAt: "2026-09-02T08:03:00.000Z",
      status: "READ",
    },
    {
      id: "m22",
      senderId: "u1",
      senderName: "Alicia Grant",
      text: "That works. I’m excited to review it together this afternoon.",
      createdAt: "2026-09-02T08:12:00.000Z",
      status: "READ",
      readBy: ["u3"],
    },
  ],
  c4: [],
  c5: [
    {
      id: "m41",
      senderId: "u4",
      senderName: "Leo Martinez",
      text: "The API timing in the last run is within target. No blockers from engineering.",
      createdAt: "2026-09-01T13:10:00.000Z",
      status: "READ",
    },
  ],
};

export const groupMembers = {
  c2: [
    {
      id: "u1",
      role: "OWNER",
      name: "Alicia Grant",
      avatar: "AG",
      color: "from-violet-500 to-indigo-500",
      status: "online",
    },
    {
      id: "u2",
      role: "ADMIN",
      name: "Noah Patel",
      avatar: "NP",
      color: "from-emerald-500 to-teal-500",
      status: "online",
    },
    {
      id: "u3",
      role: "MEMBER",
      name: "Maya Chen",
      avatar: "MC",
      color: "from-amber-500 to-orange-500",
      status: "away",
    },
    {
      id: "u5",
      role: "MEMBER",
      name: "Jules Carter",
      avatar: "JC",
      color: "from-pink-500 to-rose-500",
      status: "online",
    },
    {
      id: "u7",
      role: "MEMBER",
      name: "Priya Raman",
      avatar: "PR",
      color: "from-fuchsia-500 to-purple-500",
      status: "online",
    },
  ],
  c4: [
    {
      id: "u1",
      role: "OWNER",
      name: "Alicia Grant",
      avatar: "AG",
      color: "from-violet-500 to-indigo-500",
      status: "online",
    },
    {
      id: "u4",
      role: "ADMIN",
      name: "Leo Martinez",
      avatar: "LM",
      color: "from-cyan-500 to-sky-500",
      status: "offline",
    },
    {
      id: "u6",
      role: "MEMBER",
      name: "Ari Johnson",
      avatar: "AJ",
      color: "from-slate-500 to-gray-500",
      status: "offline",
    },
    {
      id: "u8",
      role: "MEMBER",
      name: "Nora James",
      avatar: "NJ",
      color: "from-red-500 to-pink-500",
      status: "online",
    },
  ],
};
